[package]
name = "heca"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
heca-core = { path = "../heca-core" }
heca-renderer = { path = "../heca-renderer" }
heca-config = { path = "../heca-config" }
heca-grid-ui = { path = "../heca-grid-ui" }
winit.workspace = true
wgpu = { workspace = true }
pollster = { workspace = true }
