name = "Catppuccin Latte"
background = "#eff1f5"
foreground = "#4c4f69"
border = "#ccd0da"
accent = "#1e66f5"
float_background = "#ccd0da"
float_accent = "#1e66f5"
float_focus = "#e67e22"
font_family = "Geist Mono"
font_size = 32.0
terminal_font_family = "Maple Mono Normal NF"
terminal_font_size = 14.0
border_radius = 6.0
border_width = 1.0
pane_padding = 4.0
shadow = { color = "#000000", alpha = 0.15, blur = 8.0 }
