//! The neutral property channel: [`PropInput`], [`SetProp`], [`PropName`].
//!
//! This is how a description reaches a widget **without the library ever learning that
//! descriptions exist**. `heca-grid-ui` depends on nothing above it — not `ViewNode`, not
//! `PropValue`, not the app — and that direction is settled (`AGENTS.md`: `heca` → `heca-grid-ui`,
//! never the reverse). So the library defines a plain scalar carrier, and the app converts its own
//! model into it at the boundary.
//!
//! # Why generated rather than written
//!
//! The list of properties a widget accepts used to live app-side, hand-written, one reader per
//! property. Nothing kept it in step with the library, so `Input::placeholder` and
//! `ScrollRegion`'s horizontal axis existed for months and could not be reached from a
//! description — no warning, no failing test, just a capability nobody could use.
//!
//! Now the builders *are* the list. `#[props]` on an impl block generates [`SetProp`] from the
//! builders inside it marked `#[prop]`, and the drift guard fails the build when a builder is
//! neither marked nor deliberately excluded. Adding a property is one marker; forgetting one is
//! a compile-time failure rather than a silent hole.

/// A property value as the library sees it: scalars only, no app types.
///
/// Enums travel as **names** (`"center"`, `"space_between"`, `"both"`) and are resolved by
/// [`PropName`], which the enum derives — so the variants are the vocabulary and there is no
/// parallel table of strings to maintain.
#[derive(Debug, Clone, PartialEq)]
pub enum PropInput {
    Bool(bool),
    /// One numeric channel. Callers do not have to know whether a builder wants `f32`, `usize` or
    /// `u16` — the generated conversion narrows it.
    Number(f64),
    Text(String),
}

impl PropInput {
    pub fn as_bool(&self) -> Option<bool> {
        match self {
            PropInput::Bool(b) => Some(*b),
            _ => None,
        }
    }

    /// The number, or a number written as text (`"12"`), so a description that carries everything
    /// as strings still works.
    pub fn as_f32(&self) -> Option<f32> {
        match self {
            PropInput::Number(n) => Some(*n as f32),
            PropInput::Text(t) => t.trim().parse::<f32>().ok(),
            PropInput::Bool(_) => None,
        }
    }

    pub fn as_text(&self) -> Option<&str> {
        match self {
            PropInput::Text(t) => Some(t),
            _ => None,
        }
    }
}

/// A widget's declarative property surface, generated by `#[props]` from its own builders.
///
/// By value, because that is the shape the builders already have (`fn gap(mut self, v) -> Self`);
/// a `&mut self` setter could not call them without requiring `Default` on every widget.
///
/// An unknown key returns the widget unchanged, and so does a value that does not fit the
/// builder's type — the model is untrusted input, so this stays total.
pub trait SetProp: Sized {
    /// Every property this widget exposes. The drift guard reads it.
    const PROP_NAMES: &'static [&'static str];
    /// Builders deliberately **not** exposed — closures, signal-bound setters, anything whose
    /// value cannot come from static data. Recorded so the guard can tell a considered omission
    /// from an oversight.
    const HOST_ONLY_BUILDERS: &'static [&'static str];

    /// Apply a property. Unknown key or unusable value ⇒ unchanged.
    fn set_prop(self, key: &str, value: &PropInput) -> Self;

    /// Apply a property that must land **after** children exist.
    ///
    /// `Select::selected` and `Tabs::selected` clamp against the number of options, so applying
    /// them before the options are attached would clamp against zero. Marked `#[prop(late)]`.
    fn set_late_prop(self, key: &str, value: &PropInput) -> Self;
}

/// Resolves an enum variant from its name, derived so that adding a variant extends the accepted
/// vocabulary with no string table to update.
pub trait PropName: Sized {
    const VARIANT_NAMES: &'static [&'static str];
    fn from_prop_name(name: &str) -> Option<Self>;
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::widgets::{Input, ScrollAxes, ScrollRegion};

    /// The generated surface IS the builder list — nobody wrote these names down.
    /// `placeholder` and `axes` are the two capabilities that existed in the widgets for months
    /// and could not be reached from a description; they are reachable here for free.
    #[test]
    fn the_generated_surface_comes_from_the_builders() {
        assert!(Input::PROP_NAMES.contains(&"placeholder"));
        assert!(Input::PROP_NAMES.contains(&"value"));
        assert!(ScrollRegion::PROP_NAMES.contains(&"axes"));
    }

    /// Builders that cannot come from static data are excluded automatically, by not being
    /// marked — and they are recorded, so the drift guard can tell intent from oversight.
    #[test]
    fn unmarked_builders_are_recorded_as_host_only() {
        assert!(Input::HOST_ONLY_BUILDERS.contains(&"on_change"), "a closure builder");
        assert!(ScrollRegion::HOST_ONLY_BUILDERS.contains(&"both"));
    }

    /// An enum property arrives by name, resolved from the enum's own variants.
    #[test]
    fn an_enum_property_arrives_by_name() {
        let both = ScrollRegion::new().set_prop("axes", &PropInput::Text("both".into()));
        assert_eq!(both.clone_axes(), ScrollAxes::Both);
        assert!(ScrollAxes::VARIANT_NAMES.contains(&"horizontal"));
    }

    /// Total for untrusted input: an unknown key, an unknown enum name and a wrong-typed value
    /// all leave the widget exactly as it was.
    #[test]
    fn bad_input_leaves_the_widget_alone() {
        let d = ScrollRegion::new();
        assert_eq!(d.clone_axes(), ScrollAxes::Vertical);
        let a = ScrollRegion::new().set_prop("axes", &PropInput::Text("sideways".into()));
        assert_eq!(a.clone_axes(), ScrollAxes::Vertical, "unknown variant name");
        let b = ScrollRegion::new().set_prop("nonexistent", &PropInput::Bool(true));
        assert_eq!(b.clone_axes(), ScrollAxes::Vertical, "unknown key");
        let c = Input::new().set_prop("placeholder", &PropInput::Bool(true));
        assert_eq!(c.placeholder_str(), "", "wrong type for the builder");
    }

    /// A number written as text still reaches a numeric builder — a description that carries
    /// everything as strings is a real case.
    #[test]
    fn a_number_written_as_text_still_lands() {
        assert_eq!(PropInput::Text("12.5".into()).as_f32(), Some(12.5));
        assert_eq!(PropInput::Number(3.0).as_f32(), Some(3.0));
        assert_eq!(PropInput::Bool(true).as_f32(), None);
    }
}
